# Generated by Django 3.2.11 on 2022-02-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Novice'), (1, 'Learner'), (2, 'Apprentice')]),
        ),
    ]
