# Generated by Django 3.2.13 on 2022-04-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_statement_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statement',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='solution',
            name='law',
            field=models.TextField(default='Start'),
            preserve_default=False,
        ),
    ]
