# Generated by Django 5.2.16 on 2026-07-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220418_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
    ]
