services:
  db:
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput --settings=logiclearner.settings_docker &&
               npm install &&
               trap 'kill 0' EXIT; python manage.py runserver --settings=logiclearner.settings_docker 0.0.0.0:8000 & npm run dev"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
